Kernel360/KDEV5-MY-WORK-BE

src/test/resources/sql/company-delete.sql
- company-delete.sql 샘플 데이터 누락으로 인한 빌드 실패
- 원인 : company-delete.sql 누락으로 인한 테스트 실패
- 접근 : company-delete.sql 추가
- 어떻게 테스트했는지, 테스트 결과는 어땠는지 설명해주세요.
- #6 
<br>
=> fix: 회사 샘플 데이터 누락으로 인한 빌드 실패 이슈

src/main/java/kr/mywork/common/rdb/id/UnixEpochTimeOrderedIdGenerator.java, src/main/java/kr/mywork/common/rdb/id/UnixTimeOrderedUuidGeneratedValue.java
- uuid version 7 generator 추가
- `@UnixTimeOrderedUuidGeneratedValue`
- uuid version7 을 insert 시점에 주입시켜주는 커스텀 어노테이션
- @GeneratedValue 대신 사용 권장 
- 어떻게 테스트했는지, 테스트 결과는 어땠는지 설명해주세요.
- #17 
<br>
- https://dev-cooper.tistory.com/19
- https://dev-cooper.tistory.com/69
=> feat: UUID version7 generator 추가(#17)

.gitattributes
- 커밋을 받은 branch 에서 properties 파일의 한글 텍스트가 깨지는 문제
- .gitattributes utf-8 설정 추가
- 인텔리제이에서 한글이 정상적으로 출력되는지 확인 필요
- 이후 커밋되는 한글 텍스트 데이터에서 한글 텍스트가 정상 적용될 경우, 이전 데이터 한글로 전환 예정
- #35
=> [chore] intellij 에서 messages.properties 한글 텍스트 깨지는 문제

src/main/java/kr/mywork/domain/member/model/Member.java, src/main/java/kr/mywork/domain/member/model/MemberRole.java, src/main/java/kr/mywork/domain/member/repository/MemberRepository.java, src/main/java/kr/mywork/infrastructure/member/rdb/JpaMemberRepository.java, src/main/java/kr/mywork/infrastructure/member/rdb/QueryDslMemberRepository.java
- 회원 도메인 및 역할 Enum을 정의하고, 이를 기반으로 JPA 및 QueryDSL 리포지토리를 구현했습니다.
- Member.java: 사용자 정보 엔티티 정의
- MemberRole.java: ROLE_prefix를 포함한 역할 Enum 정의
- MemberRepository.java: 도메인 계층 인터페이스 정의
- JpaMemberRepository.java: Spring Data JPA 기반 기본 구현체
- QueryDslMemberRepository.java: QueryDSL 기반 커스텀 조회 구현체
-  findByEmailAndDeletedFalse(String email) 메서드 구현
- 로그인 로직에서 Member 조회 정상 작동 확인
- query log에서 deleted = false 조건 확인됨
- #37 
<br>
- 없음
=> [feat] Member 도메인 및 Repository 구현

src/test/java/kr/mywork/docs/AuthDocumentationTest.java, src/test/java/kr/mywork/docs/CompanyDocumentationTest.java, src/test/java/kr/mywork/docs/MemberDocumentationTest.java, src/test/java/kr/mywork/docs/PostDocumentationTest.java, src/test/java/kr/mywork/docs/ProjectDocumentationTest.java, src/test/java/kr/mywork/docs/ProjectStepDocumentationTest.java, src/test/java/kr/mywork/docs/RestDocsDocumentation.java, src/test/java/kr/mywork/infrastructure/company/rdb/QueryDslCompanyRepositoryTest.java, src/test/java/kr/mywork/interfaces/post/controller/ReviewControllerTest.java, src/test/java/kr/mywork/interfaces/project_step/controller/ProjectStepControllerTest.java
- spring security 추가로 인한 테스트 빌드 실패 이슈
- @WithMockUser 제거
- AccessToken payload 로 이름 필드 추가
- 통합 테스트 AccessToken 추가 및 검증 확인
- #83
=> [fix] spring security 추가로 인한 테스트 빌드 실패 이슈

src/main/java/kr/mywork/domain/project/model/ProjectMember.java, src/main/java/kr/mywork/domain/project_member/repository/ProjectMemberRepository.java, src/main/java/kr/mywork/domain/project_member/service/ProjectMemberService.java, src/main/java/kr/mywork/infrastructure/project_member/rdb/JpaProjectMemberRepository.java, src/main/java/kr/mywork/infrastructure/project_member/rdb/QueryDslProjectMemberRepository.java, src/main/java/kr/mywork/interfaces/project_member/controller/ProjectMemberController.java, src/main/java/kr/mywork/interfaces/project_member/controller/dto/response/ProjectMemberAddWebResponse.java, src/test/java/kr/mywork/docs/ProjectMemberDocumentationTest.java
프로젝트 멤버 할당 API
- 프로젝트 멤버를 할당합니다.
#72
=> [feat] 프로젝트 멤버 할당 API

src/main/java/kr/mywork/domain/project_checklist/errors/ProjectCheckListErrorCode.java, src/main/java/kr/mywork/domain/project_checklist/errors/ProjectCheckListErrorType.java, src/main/java/kr/mywork/domain/project_checklist/errors/ProjectCheckListException.java, src/main/java/kr/mywork/domain/project_checklist/errors/ProjectCheckListNotFoundException.java, src/main/java/kr/mywork/domain/project_checklist/model/ProjectCheckList.java, src/main/java/kr/mywork/domain/project_checklist/repository/ProjectCheckListRepository.java, src/main/java/kr/mywork/domain/project_checklist/service/ProjectCheckListService.java, src/main/java/kr/mywork/domain/project_checklist/service/dto/request/ProjectCheckListCreateRequest.java, src/main/java/kr/mywork/domain/project_checklist/service/dto/response/ProjectCheckListCreateResponse.java, src/main/java/kr/mywork/domain/project_checklist/service/dto/response/ProjectCheckListDetailResponse.java, src/main/java/kr/mywork/infrastructure/project_checklist/rdb/QueryDslProjectCheckListRepository.java, src/main/java/kr/mywork/interfaces/project_checklist/controller/ProjectCheckListController.java, src/main/java/kr/mywork/interfaces/project_checklist/controller/dto/request/ProjectCheckListCreateWebRequest.java, src/main/java/kr/mywork/interfaces/project_checklist/controller/dto/response/ProjectCheckListCreateWebResponse.java, src/main/java/kr/mywork/interfaces/project_checklist/controller/dto/response/ProjectCheckListDetailWebResponse.java, src/test/java/kr/mywork/docs/ProjectCheckListDocumentationTest.java, src/test/resources/sql/project-check-list-for-get.sql
- 체크리스트 상세조회 API
- 체크리스트 상세조회 API구현합니다.
요청, 응답 :
쿼리 결과 : 
```zsh
Hibernate: select pcl1_0.id,pcl1_0.approval,pcl1_0.client_company_id,pcl1_0.created_at,pcl1_0.dev_company_id,pcl1_0.project_step_id,pcl1_0.title from project_check_list pcl1_0 where pcl1_0.id=?
```
- #90 
<br>
=> 체크리스트 상세조회 API

src/main/java/kr/mywork/domain/member/service/MemberService.java, src/main/java/kr/mywork/domain/member/service/dto/request/MemberUpdateRequest.java, src/main/java/kr/mywork/domain/member/service/dto/response/MemberSelectResponse.java, src/main/java/kr/mywork/infrastructure/member/rdb/QueryDslMemberRepository.java, src/main/java/kr/mywork/interfaces/member/controller/dto/response/MemberSelectWebResponse.java, src/test/java/kr/mywork/docs/MemberDocumentationTest.java
회원 목록 조회시 ID값 추가
-  회원목록 조회시 상세 페이지 이동을 위한 ID값 추가.
#112 
#41 
<br>
=> [fix] 회원 목록 조회시 ID값 추가

src/main/java/kr/mywork/domain/project_step/model/ProjectStep.java, src/main/java/kr/mywork/domain/project_step/serivce/ProjectStepService.java, src/main/java/kr/mywork/domain/project_step/serivce/dto/request/ProjectStepCreateRequest.java
- 프로젝트 스탭 생성 API 수정
- 프로젝트 스탭 생성시 projectId 추가
- 중복 방지 엔티티에 추가
통합테스트
#122 
#33
=> fix: 프로젝트 스탭 생성시 projectId 추가

src/main/java/kr/mywork/domain/company/service/dto/response/MemberDetailResponse.java, src/main/java/kr/mywork/domain/member/service/dto/response/MemberProjectInfoResponse.java, src/main/java/kr/mywork/domain/project/repository/ProjectRepository.java, src/main/java/kr/mywork/domain/project/service/ProjectService.java, src/main/java/kr/mywork/infrastructure/member/rdb/QueryDslMemberRepository.java, src/main/java/kr/mywork/infrastructure/project/rdb/QueryDslProjectRepository.java, src/main/java/kr/mywork/interfaces/member/controller/MemberController.java, src/main/java/kr/mywork/interfaces/member/controller/dto/response/MemberDetailsWebResponse.java, src/main/java/kr/mywork/interfaces/member/controller/dto/response/MemberProjectInfoWebResponse.java, src/test/java/kr/mywork/docs/MemberDocumentationTest.java, src/test/resources/sql/member-get-detail.sql
멤버 상세 조회 필드 추가
- 프로젝트 리스트 및 회사전화번호 , 생성일 ,수정일 값을 추가함
- 해당 PR 과 연관된 이슈를 연결해 주세요.
#136  - fix 수정 이슈
#120 - 기존작업
=> [fix]  멤버 상세 조회 필드 추가

src/main/java/kr/mywork/common/auth/components/annotation/LoginMember.java, src/main/java/kr/mywork/common/auth/components/argument_resolver/LoginUserArgumentResolver.java, src/main/java/kr/mywork/common/auth/components/dto/LoginMemberDetail.java, src/main/java/kr/mywork/common/auth/config/AuthenticationArgumentConfig.java, src/main/java/kr/mywork/common/auth/config/JwtProperties.java, src/main/java/kr/mywork/common/auth/config/SecurityConfig.java, src/main/java/kr/mywork/domain/auth/service/JwtTokenProvider.java, src/main/java/kr/mywork/interfaces/company/controller/CompanyController.java
- 컨트롤러 파라미터에 인증 정보 전달 로직 추가
- 컨트롤러 인증 정보 전달 ArgumentResolver 개발
- #154
=> [feat] 컨트롤러 파라미터에 인증 정보 전달 로직 추가

src/main/java/kr/mywork/common/auth/config/SecurityConfig.java
- 임시 CORS 허용 URL 추가
- HTTPS 적용 과정에서 AWS ACM 의 인증서 발급 대기로 인한 개발 서버 환경 테스트를 위한 임시 URL 추가
테스트 코드 추가 변화가 없습니다.
- #166
=> [feat] 임시 CORS 허용 URL 추가

src/main/java/kr/mywork/interfaces/company/controller/CompanyController.java, src/test/java/kr/mywork/docs/CompanyDocumentationTest.java
- 회사 삭제 API 수정
회사 삭제 API  변경 값을 하나만 받지만 requestBody로받음
pathvariable 로 변경 프론트 호출 형식과동일하게 변경
- 화면 테스트 완료.
#176
=> fix : 회사 삭제 API 수정

src/main/java/kr/mywork/common/auth/components/argument_resolver/LoginUserArgumentResolver.java, src/main/java/kr/mywork/common/auth/components/dto/LoginMemberDetail.java, src/main/java/kr/mywork/common/auth/config/SecurityConfig.java, src/main/java/kr/mywork/domain/dashboard/service/DashboardService.java, src/main/java/kr/mywork/domain/dashboard/service/dto/response/CompanyAdminProjectResponse.java, src/main/java/kr/mywork/domain/dashboard/service/dto/response/DashboardCountSummaryResponse.java, src/main/java/kr/mywork/domain/dashboard/service/errors/DashboardErrorCode.java, src/main/java/kr/mywork/domain/dashboard/service/errors/DashboardErrorType.java, src/main/java/kr/mywork/domain/dashboard/service/errors/DashboardException.java, src/main/java/kr/mywork/domain/dashboard/service/errors/DashboardTypeNotFoundException.java, src/main/java/kr/mywork/domain/dashboard/service/repository/DashboardRepository.java, src/main/java/kr/mywork/infrastructure/dashboard/rdb/QueryDslDashboardRepository.java, src/main/java/kr/mywork/interfaces/dashboard/controller/DashboardController.java, src/main/java/kr/mywork/interfaces/dashboard/controller/dto/request/DashboardCountSummaryWebRequest.java, src/main/java/kr/mywork/interfaces/dashboard/controller/dto/response/DashboardCountSummaryWebResponse.java, src/main/java/kr/mywork/interfaces/dashboard/controller/errors/handler/DashboardControllerAdvice.java, src/test/java/kr/mywork/docs/DashboardDocumentationTest.java, src/test/resources/sql/dashboard-summery-count.sql
- 대시보드 써머리 조회 API
- 대시보드 써머리 조회 API
-통합테스 및 포스트맨 
#206
=> [feat] 대시보드 써머리 조회 API

scripts/start.sh
- 스크립트 내부 사용자 로그 쓰기 권한 추가
- 스크립트 내부 사용자 로그 쓰기 권한 추가
```bash
#!/bin/bash
JAR_PATH=/home/ec2-user/deploy/mywork-be-0.0.1-SNAPSHOT.jar
APP_NAME=mywork-be-0.0.1-SNAPSHOT
PID=$(pgrep -f $APP_NAME)
if [ -n "$PID" ]; then
kill -9 $PID
fi
mkdir -p ../log/info
mkdir -p ../log/warn
mkdir -p ../log/error
sudo chown -R ec2-user:ec2-user ../log # 이 부분
nohup java -jar $JAR_PATH --spring.profiles.active=prod --spring.config.location=file:/home/ec2-user/config/application-prod.yml > /home/ec2-user/deploy/nohup.out 2>&1 &
```
- 개발 환경에서 1차 확인
- 없음
=> [build] 스크립트 내부 사용자 로그 쓰기 권한 추가

src/main/java/kr/mywork/domain/company/model/Company.java, src/main/java/kr/mywork/domain/company/service/CompanyImageService.java
- 회사 이미지 메타데이터 저장 로직 추가
- 회사 이미지 메타데이터 저장 로직 추가
- 이미지가 없을 경우에만 업로드 가능
- 현재 단계 테스트 검증 완료
- #273 
<br>
- 없음
=> [feat] 회사 이미지 메타데이터 저장 로직 추가 (#273)

docker/docker-compose.yml
LocalStack CORS 설정을 통해 프론트엔드에서 S3 프리사인드 URL 파일 업로드 시 발생하는 CORS 에러를 해결했습니다.
- 도커 컴포즈파일에 CORS 환경변수 추가하였습니다.
- #281
=> localstack container CORS 환경변수 추가

src/main/java/kr/mywork/common/schedules/ScheduleConfig.java, src/main/java/kr/mywork/domain/post/model/PostId.java, src/main/java/kr/mywork/domain/post/repository/PostIdRepository.java, src/main/java/kr/mywork/domain/post/service/PostIdService.java, src/main/java/kr/mywork/domain/post/service/PostService.java, src/main/java/kr/mywork/infrastructure/post/rdb/QueryDslPostIdRepository.java, src/main/java/kr/mywork/interfaces/post/controller/PostController.java, src/main/java/kr/mywork/interfaces/post/controller/PostIdController.java, src/main/java/kr/mywork/interfaces/post/scheduler/PostIdDeleteScheduler.java, src/main/resources/application.yml, src/test/java/kr/mywork/infrastructure/post/rdb/QueryDslPostIdRepositoryTest.java, src/test/resources/application.yml, src/test/resources/sql/issued-post-id-bulk-deletion.sql, src/test/resources/sql/post-for-approve.sql, src/test/resources/sql/post-for-delete.sql, src/test/resources/sql/post-for-get-list.sql, src/test/resources/sql/post-for-get.sql, src/test/resources/sql/post-for-update.sql, src/test/resources/sql/post-id.sql
- 게시글 발급 아이디 일괄 삭제 스케줄러 추가
- 오전 4시 발급 아이디 일괄 삭제 스케줄러 구성
- 발급 시간 기준 24시간 지난 게시글 발급 아이디 삭제
- 스케줄러 구성으로 인한 오전 4시 실행 확인 필요
- 일괄 삭제 레포지토리 삭제 테스트 추가
- #285 
<br>
- 없음
=> [feat] 게시글 발급 아이디 일괄 삭제 스케줄러 추가

src/main/java/kr/mywork/domain/notification/model/NotificationActionType.java, src/main/java/kr/mywork/domain/post/service/ReviewService.java, src/test/java/kr/mywork/docs/ReviewDocumentationTest.java, src/test/java/kr/mywork/domain/post/service/ReviewServiceTest.java, src/test/resources/sql/review-create-test.sql
게시글에 댓글이 달릴 경우 게시글 작성자에게 알림이 가도록 알림 전송 기능을 추가했습니다. 기존 승인 알림 구조와 동일하게 `NotificationService.save()`를 활용하였습니다.
---
* 게시글 댓글 작성 시 게시글 작성자에게 알림 저장 로직 추가
* `NotificationActionType`에 `REVIEW` 타입 추가
* 게시글, 프로젝트 단계 연관 객체 조회 로직 추가
* 자기 자신에게는 알림이 가지 않도록 예외 처리
---
---
* 다른 사용자가 댓글 작성 시 게시글 작성자에게 알림 정상 생성됨
* 댓글 작성자가 게시글 작성자인 경우 알림 생성되지 않음
* 알림 조회 API (`GET /notifications`)에서 해당 알림 정상적으로 노출됨
---
* #260
* #294 
---
* 내부 비즈니스 로직에 기반하여 작성됨
=> [feat] 댓글 작성 시 게시글 작성자에게 알림 전송 기능 및 관련 알림 타입 구조 개선(#294)

src/main/java/kr/mywork/domain/notification/service/dto/response/NotificationSelectResponse.java, src/main/java/kr/mywork/infrastructure/notification/rdb/QueryDslNotificationRepository.java, src/main/java/kr/mywork/interfaces/notification/controller/dto/response/NotificationSelectWebResponse.java
* 알림 읽음 여부(`isRead`)를 프론트에서 표시할 수 있도록 응답 DTO에 해당 필드를 추가했습니다.
* `NotificationSelectResponse` DTO에 `isRead` 필드 추가
* 생성자에 `isRead` 파라미터 추가 및 필드 매핑
* `NotificationSelectWebResponse` DTO에도 `isRead` 필드 추가
* `.from()` 메서드에서 `isRead` 포함하도록 수정
* API 호출 시 응답 JSON에 `isRead` 필드가 포함되어 정상적으로 반환되는 것 확인
* 기존 알림 목록 조회 API 동작 정상
* #260 
* 없음
=> feat: 알림 응답 DTO에 isRead 필드 추가(#296)

src/main/java/kr/mywork/domain/notification/repository/NotificationRepository.java, src/main/java/kr/mywork/domain/notification/service/NotificationService.java, src/main/java/kr/mywork/infrastructure/notification/rdb/QueryDslNotificationRepository.java, src/main/java/kr/mywork/interfaces/notification/controller/NotificationController.java
* 사용자의 읽지 않은 알림 개수를 조회할 수 있는 API를 구현했습니다.
* 사이드바나 헤더 등에서 뱃지로 표시할 수 있도록 프론트와 연동될 예정입니다.
* GET `/api/notifications/unread-count` API 엔드포인트 추가
* `NotificationService`에 `countUnreadNotifications()` 메서드 구현
* `NotificationRepository`에 `countByMemberIdAndIsReadFalse()` 메서드 추가
* 로그인한 사용자의 읽지 않은 알림 개수를 반환
* Postman으로 테스트 시, 로그인 사용자 기준으로 알림 테이블의 isRead = false 개수가 정확히 반환됨
* #298 
* #296 
* #294 
* #260 
* 없음
=> [feat] 안읽은 알림 개수 조회 API 추가 (#298)

src/main/java/kr/mywork/infrastructure/post/rdb/QueryDslPostRepository.java
- 프로젝트 스탭 갯수 조회시 삭제된건은 제외
-  프로젝트 스탭 갯수 조회시 삭제된건은 제외
화면 테스트
#305
=> [bug]  프로젝트 스탭 갯수 조회시 삭제된건은 제외

src/main/java/kr/mywork/domain/post/service/dto/request/ReviewCreateRequest.java
- 리뷰에 작성자 이름과 회사 이름이 반대로 들어가는 이슈
- 데이터 저장 순서 변경
- 어떻게 테스트했는지, 테스트 결과는 어땠는지 설명해주세요.
- #303 
<br>
- 없음
=> [fix] 리뷰에 작성자 이름과 회사 이름이 반대로 들어가는 이슈

src/main/java/kr/mywork/domain/auth/service/TokenAuthenticationService.java, src/main/java/kr/mywork/domain/member/model/Member.java, src/main/java/kr/mywork/domain/member/model/MemberRole.java, src/main/java/kr/mywork/domain/project/service/ProjectDashBoardService.java, src/main/java/kr/mywork/domain/project/service/ProjectService.java, src/main/java/kr/mywork/infrastructure/project/rdb/QueryDslProjectRepository.java, src/main/java/kr/mywork/interfaces/dashboard/controller/DashboardController.java, src/test/java/kr/mywork/infrastructure/project/rdb/QueryDslProjectRepositoryTest.java, src/test/resources/sql/projects_near_deadline02.sql
- 고객사 어드민 대시보드 접근 시 5일 이내 대시보드에서 6일 이전 내용이 조회되는 문제
- PostService & PostDashboardSerivce 분리
- querydsl where 절 조건 수정
- 해당 이슈 참고
- #316
- 없음
=> [fix] 고객사 어드민 대시보드 접근 시 5일 이내 대시보드에서 6일 이전 내용이 조회되는 문제

src/main/java/kr/mywork/infrastructure/company/rdb/QueryDslCompanyRepository.java, src/main/java/kr/mywork/interfaces/company/controller/CompanyController.java
* 회사 목록 API에서 `companyType` 파라미터가 누락될 경우 예외가 발생하던 문제를 수정하였습니다.
* QueryDSL 조건절에서 `eq(null)` 호출로 인해 발생하던 런타임 오류를 방지하도록 수정하였습니다.
* `@RequestParam(name = "companyType")` → `@RequestParam(name = "companyType", required = false)`로 수정하여 파라미터 optional 처리
* `company.type.stringValue().eq(companyType)` → `eqCompanyType(companyType)` 메서드로 변경하여 null-safe 쿼리 적용
* `eqCompanyType(String companyType)` 메서드 추가: null일 경우 조건 생략 처리
* `countTotalCompaniesByCondition` 및 `findCompaniesBySearchConditionWithPaging`에서 위 조건 적용
* `companyType` 없이 호출 시 전체 회사 목록 정상 조회됨
* 이전에 발생하던 `InvalidDataAccessApiUsageException: eq(null) is not allowed` 예외 재현되지 않음
* 프론트에서 페이지 로딩 및 필터링 동작 모두 정상 작동 확인
* 없음
* 없음
=> [fix] companyType` 파라미터 누락 시 예외 발생 문제 수정 및 QueryDSL 조건 null-safe 처리(#320)

src/main/java/kr/mywork/common/api/components/interceptor/PermissionCheckInterceptor.java, src/main/java/kr/mywork/common/api/config/WebConfig.java, src/main/java/kr/mywork/domain/project/errors/ProjectErrorCode.java, src/main/java/kr/mywork/domain/project/errors/ProjectErrorType.java, src/main/java/kr/mywork/domain/project/model/Project.java, src/main/java/kr/mywork/domain/project/model/ProjectMember.java, src/main/java/kr/mywork/domain/project/service/ProjectService.java, src/main/java/kr/mywork/domain/project_member/repository/ProjectMemberRepository.java, src/main/java/kr/mywork/domain/project_member/service/ProjectMemberService.java, src/main/java/kr/mywork/domain/project_member/service/dto/request/ProjectManagerUpdateRequest.java, src/main/java/kr/mywork/infrastructure/project_member/rdb/QueryDslProjectMemberRepository.java, src/main/java/kr/mywork/interfaces/project/controller/ProjectController.java, src/main/java/kr/mywork/interfaces/project/controller/dto/response/ProjectStatusUpdateWebResponse.java, src/main/java/kr/mywork/interfaces/project_member/controller/ProjectMemberController.java, src/main/java/kr/mywork/interfaces/project_member/controller/dto/request/ProjectManagerUpdateWebRequest.java, src/main/java/kr/mywork/interfaces/project_member/controller/dto/response/ProjectManagerUpdateWebResponse.java, src/test/java/kr/mywork/docs/ProjectDocumentationTest.java, src/test/java/kr/mywork/docs/ProjectMemberDocumentationTest.java, src/test/java/kr/mywork/interfaces/post/controller/PostControllerTest.java, src/test/java/kr/mywork/interfaces/project_step/controller/ProjectStepControllerTest.java, src/test/resources/sql/project-manager.sql, src/test/resources/sql/project-status-update.sql
- 프로젝트 매니저 상태값 변경  기능 추가
- 프로젝트 매니저 상태값 변경  기능 추가
- 프로젝트 상태값 변경 api 추가 
- 프로젝트 상태값 변경에 대한 인터셉터 추가
- 프로젝트 인터셉터에 의한 수정.
- post맨 테스트 
#317
=> feat: 프로젝트 매니저 상태값 변경  기능 추가

src/main/java/kr/mywork/common/api/components/interceptor/PermissionCheckInterceptor.java, src/main/java/kr/mywork/common/api/config/WebConfig.java, src/main/java/kr/mywork/domain/project/errors/ProjectErrorCode.java, src/main/java/kr/mywork/domain/project/errors/ProjectErrorType.java, src/main/java/kr/mywork/domain/project/model/Project.java, src/main/java/kr/mywork/domain/project/model/ProjectMember.java, src/main/java/kr/mywork/domain/project/service/ProjectService.java, src/main/java/kr/mywork/domain/project_member/repository/ProjectMemberRepository.java, src/main/java/kr/mywork/domain/project_member/service/ProjectMemberService.java, src/main/java/kr/mywork/domain/project_member/service/dto/request/ProjectManagerUpdateRequest.java, src/main/java/kr/mywork/domain/project_member/service/dto/response/ProjectMemberDto.java, src/main/java/kr/mywork/infrastructure/project_member/rdb/QueryDslProjectMemberRepository.java, src/main/java/kr/mywork/interfaces/project/controller/ProjectController.java, src/main/java/kr/mywork/interfaces/project/controller/dto/response/ProjectStatusUpdateResponse.java, src/main/java/kr/mywork/interfaces/project/controller/dto/response/ProjectStatusUpdateWebResponse.java, src/main/java/kr/mywork/interfaces/project_member/controller/ProjectMemberController.java, src/main/java/kr/mywork/interfaces/project_member/controller/dto/request/ProjectManagerUpdateWebRequest.java, src/main/java/kr/mywork/interfaces/project_member/controller/dto/response/ProjectManagerUpdateWebResponse.java, src/test/java/kr/mywork/docs/ProjectDocumentationTest.java, src/test/java/kr/mywork/docs/ProjectMemberDocumentationTest.java, src/test/java/kr/mywork/interfaces/post/controller/PostControllerTest.java, src/test/java/kr/mywork/interfaces/project_step/controller/ProjectStepControllerTest.java, src/test/resources/sql/project-manager.sql, src/test/resources/sql/project-status-update.sql
- 프로젝트 상태값 변경시 프로젝트 매니저만 가능하도록 수정
- 프로젝트 상태값 변경시 프로젝트 매니저만 가능하도록 수정 
-포스트맨 테스트
#323
=> 프로젝트 상태값 변경시 프로젝트 매니저만 가능하도록 수정 
