build.gradle, src/main/java/kr/mywork/common/api/components/handler/InvalidRequestArgsControllerAdvice.java, src/main/java/kr/mywork/common/api/support/error/CommonErrorCode.java, src/main/java/kr/mywork/common/api/support/error/CommonErrorType.java, src/main/java/kr/mywork/interfaces/company/controller/dto/request/CompanyCreateWebRequest.java, src/main/resources/application.yml
요청 입력 값 처리를 위한 설정 추가
- Hibernate Validator 의존성 추가
- MessageSource 설정 추가
- 코드 값을 기반으로 다른 예외 메시지를 응답하기 위함
- 여러 메시지 값을 반환하는 경우 구분자 `/` 을 통해서 구분
- #3 
<br>
- https://docs.spring.io/spring-boot/reference/io/validation.html
=> [feat] 입력 요청값 유효성 검증을 위한 설정

src/main/java/kr/mywork/domain/company/model/Company.java, src/main/java/kr/mywork/domain/company/service/CompanyService.java, src/main/java/kr/mywork/domain/company/service/dto/response/CompanyDetailResponse.java, src/main/java/kr/mywork/interfaces/company/controller/CompanyController.java, src/main/java/kr/mywork/interfaces/company/controller/dto/response/CompanyDetailWebResponse.java, src/test/java/kr/mywork/docs/CompanyDocumentationTest.java, src/test/resources/sql/company-detail.sql
- 어떤 작업을 했는지 간단히 설명해주세요.
- 주요 변경 사항을 bullet point로 작성해주세요.
- 예:
- 로그인 API 기능 추가
- 회원가입 오류 처리 로직 수정
- 로컬 환경 테스트 정상 동작 확인
- #20
<br>
=> [feat] 회사 상세 조회 API 개발

src/main/java/kr/mywork/domain/post/model/Post.java, src/main/java/kr/mywork/domain/post/model/PostAttachment.java, src/main/java/kr/mywork/domain/post/model/Review.java, src/main/java/kr/mywork/domain/projectCheckList/model/ProjectCheckList.java, src/main/java/kr/mywork/domain/projectCheckList/model/ProjectCheckListHistory.java, src/main/java/kr/mywork/domain/projectStep/model/ProjectStep.java
- 업무,진천관리 관련 Entity 작성하였습니다.
작성한 엔티티
- Post
- PostAttachment
- Review
- ProjectCheckList
- ProjectCheckListHistory
- ProjectStep
- 기존 기능 테스트는 잘 작동합니다.
- 해당 PR 과 연관된 이슈를 연결해 주세요.
- #25
=> feat : 업무관리, 진척관리 관련 Entity 작성(#25)

src/main/java/kr/mywork/domain/post/errors/PostErrorCode.java, src/main/java/kr/mywork/domain/post/errors/PostErrorType.java, src/main/java/kr/mywork/domain/post/errors/PostException.java, src/main/java/kr/mywork/domain/post/errors/PostIdNotFoundException.java, src/main/java/kr/mywork/domain/post/errors/PostNotFoundException.java, src/main/java/kr/mywork/domain/post/model/Post.java, src/main/java/kr/mywork/domain/post/model/PostId.java, src/main/java/kr/mywork/domain/post/repository/PostIdRepository.java, src/main/java/kr/mywork/domain/post/repository/PostRepository.java, src/main/java/kr/mywork/domain/post/service/PostService.java, src/main/java/kr/mywork/domain/post/service/dto/request/PostCreateRequest.java, src/main/java/kr/mywork/domain/post/service/dto/response/PostCreateResponse.java, src/main/java/kr/mywork/domain/project_checklist/model/ProjectCheckList.java, src/main/java/kr/mywork/domain/project_checklist/model/ProjectCheckListHistory.java, src/main/java/kr/mywork/domain/project_step/model/ProjectStep.java, src/main/java/kr/mywork/infrastructure/post/rdb/JpaPostIdRepository.java, src/main/java/kr/mywork/infrastructure/post/rdb/JpaPostRepository.java, src/main/java/kr/mywork/infrastructure/post/rdb/QueryDslPostIdRepository.java, src/main/java/kr/mywork/infrastructure/post/rdb/QueryDslPostRepository.java, src/main/java/kr/mywork/interfaces/post/controller/PostController.java, src/main/java/kr/mywork/interfaces/post/controller/dto/request/PostCreateWebRequest.java, src/main/java/kr/mywork/interfaces/post/controller/dto/response/PostCreateWebResponse.java, src/main/java/kr/mywork/interfaces/post/controller/dto/response/PostIdCreateWebResponse.java, src/main/java/kr/mywork/interfaces/post/controller/errors/handler/PostControllerAdvice.java, src/test/java/kr/mywork/docs/PostDocumentationTest.java, src/test/resources/sql/post-id.sql
- 게시글 생성 API 와 게시글 ID 생성 작업하였습니다.
- 게시글 생성 API 
- 게시글 ID 생성 API
- 게시글 ID 생성 API 쿼리 결과 : 
```zsh
Hibernate: select pi1_0.id from post_id pi1_0 where pi1_0.id=?
Hibernate: insert into post_id (id) values (?)
```
- 게시글 생성 API 쿼리 결과 : 
```zsh
Hibernate: select pi1_0.id from post_id pi1_0 where pi1_0.id=? limit ?
Hibernate: select p1_0.id,p1_0.approval,p1_0.author_name,p1_0.company_name,p1_0.content,p1_0.created_at,p1_0.deleted,p1_0.modified_at,p1_0.project_step_id,p1_0.title from post p1_0 where p1_0.id=?
Hibernate: insert into post (approval,author_name,company_name,content,created_at,deleted,modified_at,project_step_id,title,id) values (?,?,?,?,?,?,?,?,?,?)
```
- 요청
-응답
- 요청
- 응답
- #34 
<br>
=> 게시글 ID 생성, 게시글 생성 API

src/main/java/kr/mywork/domain/member/errors/MemberErrorCode.java, src/main/java/kr/mywork/domain/member/errors/MemberErrorType.java, src/main/java/kr/mywork/domain/member/errors/MemberException.java, src/main/java/kr/mywork/domain/member/errors/MemberTypeNotFoundException.java, src/main/java/kr/mywork/domain/member/model/Member.java, src/main/java/kr/mywork/domain/member/repository/MemberRepository.java, src/main/java/kr/mywork/domain/member/service/MemberService.java, src/main/java/kr/mywork/domain/member/service/dto/response/CompanyMemberResponse.java, src/main/java/kr/mywork/infrastructure/company/rdb/JpaCompanyRepository.java, src/main/java/kr/mywork/infrastructure/member/rdb/JpaMemberRepository.java, src/main/java/kr/mywork/infrastructure/member/rdb/QueryDslMemberRepository.java, src/main/java/kr/mywork/interfaces/member/controller/MemberController.java, src/main/java/kr/mywork/interfaces/member/controller/dto/response/CompanyMemberWebResponse.java, src/main/java/kr/mywork/interfaces/member/controller/dto/response/MemberListWebResponse.java, src/test/java/kr/mywork/docs/MemberDocumentationTest.java, src/test/resources/sql/company-member-get.sql
=> [feat] Company 직원 조회 API

src/main/java/kr/mywork/domain/member/repository/MemberRepository.java, src/main/java/kr/mywork/domain/member/service/MemberService.java, src/main/java/kr/mywork/infrastructure/member/rdb/QueryDslMemberRepository.java, src/main/java/kr/mywork/interfaces/member/controller/MemberController.java, src/main/java/kr/mywork/interfaces/member/controller/dto/response/MemberListWebResponse.java, src/main/resources/application.yml, src/test/java/kr/mywork/docs/MemberDocumentationTest.java
회사 직원 조회시 들어가는 값 페이징에 대한 검증 로직 추가
#51
=> [feat] 회사직원 조회 페이징 검증

src/main/java/kr/mywork/interfaces/company/controller/CompanyController.java, src/test/java/kr/mywork/docs/CompanyDocumentationTest.java
- 회사 URL root path 변경
- /company -> /companies 변경
#98
=> [refactor] 회사 URL root path 변경 (#98)

src/main/java/kr/mywork/domain/project_checklist/errors/ProjectCheckListErrorCode.java, src/main/java/kr/mywork/domain/project_checklist/errors/ProjectCheckListErrorType.java, src/main/java/kr/mywork/domain/project_checklist/errors/ProjectCheckListException.java, src/main/java/kr/mywork/domain/project_checklist/errors/ProjectCheckListNotFoundException.java, src/main/java/kr/mywork/domain/project_checklist/model/ProjectCheckList.java, src/main/java/kr/mywork/domain/project_checklist/repository/ProjectCheckListRepository.java, src/main/java/kr/mywork/domain/project_checklist/service/ProjectCheckListService.java, src/main/java/kr/mywork/domain/project_checklist/service/dto/request/ProjectCheckListCreateRequest.java, src/main/java/kr/mywork/domain/project_checklist/service/dto/request/ProjectCheckListUpdateRequest.java, src/main/java/kr/mywork/domain/project_checklist/service/dto/response/ProjectCheckListCreateResponse.java, src/main/java/kr/mywork/domain/project_checklist/service/dto/response/ProjectCheckListDetailResponse.java, src/main/java/kr/mywork/domain/project_checklist/service/dto/response/ProjectCheckListUpdateResponse.java, src/main/java/kr/mywork/infrastructure/project_checklist/rdb/QueryDslProjectCheckListRepository.java, src/main/java/kr/mywork/interfaces/project_checklist/controller/ProjectCheckListController.java, src/main/java/kr/mywork/interfaces/project_checklist/controller/dto/request/ProjectCheckListCreateWebRequest.java, src/main/java/kr/mywork/interfaces/project_checklist/controller/dto/request/ProjectCheckListUpdateWebRequest.java, src/main/java/kr/mywork/interfaces/project_checklist/controller/dto/response/ProjectCheckListCreateWebResponse.java, src/main/java/kr/mywork/interfaces/project_checklist/controller/dto/response/ProjectCheckListDetailWebResponse.java, src/main/java/kr/mywork/interfaces/project_checklist/controller/dto/response/ProjectCheckListUpdateWebResponse.java, src/test/java/kr/mywork/docs/ProjectCheckListDocumentationTest.java, src/test/resources/sql/project-check-list-for-get.sql, src/test/resources/sql/project-check-list-for-update.sql
체크리스트 수정 API
체크리스트 수정 API를 구현합니다.
응답, 요청
쿼리결과 : 
```zsh
Hibernate: select pcl1_0.id,pcl1_0.approval,pcl1_0.client_company_id,pcl1_0.created_at,pcl1_0.dev_company_id,pcl1_0.project_step_id,pcl1_0.title from project_check_list pcl1_0 where pcl1_0.id=?
```
- #96 
<br>
=> [feat] 체크리스트 수정 API

build.gradle
- API 문서화 요청 URL 동적 변경
- 동적으로 요청 URL 설정 가능
- #107 
<br>
- https://github.com/OAI/OpenAPI-Specification/blob/main/versions/3.0.1.md#server-object
- https://github.com/ePages-de/restdocs-api-spec?tab=readme-ov-file
=> [feat] API 문서화 요청 URL 동적 변경

src/main/java/kr/mywork/domain/auth/dto/MemberDetails.java, src/main/java/kr/mywork/domain/auth/dto/response/TokenResponse.java, src/main/java/kr/mywork/domain/auth/service/JwtTokenProvider.java, src/main/java/kr/mywork/domain/auth/service/MemberDetailService.java, src/main/java/kr/mywork/domain/auth/service/TokenAuthenticationService.java, src/main/java/kr/mywork/domain/auth/service/TokenService.java, src/main/java/kr/mywork/interfaces/auth/dto/response/TokenWebResponse.java, src/main/java/kr/mywork/interfaces/auth/handler/success/LoginSuccessHandler.java, src/test/java/kr/mywork/docs/AuthDocumentationTest.java, src/test/java/kr/mywork/docs/RestDocsDocumentation.java, src/test/resources/sql/member-auth.sql
-로그인시 받을 정보추가 #114 
- 로그인시 토큰에 companyId와 companyName companyLogo companyType을 같이 내려줌
#114 
#30
=> [fix] 로그인시 받을 정보추가

src/main/java/kr/mywork/domain/member/repository/MemberRepository.java, src/main/java/kr/mywork/domain/member/service/MemberService.java, src/main/java/kr/mywork/domain/member/service/dto/response/MemberSelectResponse.java, src/main/java/kr/mywork/domain/project_member/repository/ProjectMemberRepository.java, src/main/java/kr/mywork/domain/project_member/service/ProjectMemberService.java, src/main/java/kr/mywork/domain/project_member/service/dto/response/CompanyMemberInProjectResponse.java, src/main/java/kr/mywork/domain/project_member/service/dto/response/CompanyMemberInProjectSelectResponse.java, src/main/java/kr/mywork/infrastructure/member/rdb/QueryDslMemberRepository.java, src/main/java/kr/mywork/infrastructure/project_member/rdb/QueryDslProjectMemberRepository.java, src/main/java/kr/mywork/interfaces/member/controller/MemberController.java, src/main/java/kr/mywork/interfaces/member/controller/dto/response/MemberSelectWebResponse.java, src/main/java/kr/mywork/interfaces/project_member/controller/ProjectMemberController.java, src/main/java/kr/mywork/interfaces/project_member/controller/dto/response/CompanyMembersInProjectWebResponse.java, src/test/java/kr/mywork/docs/MemberDocumentationTest.java, src/test/java/kr/mywork/docs/ProjectMemberDocumentationTest.java, src/test/resources/sql/member-auth.sql, src/test/resources/sql/member-search.sql, src/test/resources/sql/project-member-get.sql
- 프로젝트 직원 목록 조회 API
- 프로젝트 직원 목록을 조회한다.\
- projectId  와 companyId를 받아서
- memberId , memberName , email 을 리턴한다.
통합테스트
포스트맨 총 멤버3 명    프로젝트 소속된 멤버 2명
#116
=> 프로젝트 직원 목록 조회

src/main/java/kr/mywork/domain/project_step/model/ProjectStep.java
- 프로젝트 스탭 엔티티 수정 
- 프로젝트 스탭 엔티티 수정  
이유: 프로젝트 엔티티에 추가된 부분으로 인해 프로젝트 스탭 수정에 영향도가 생겨 롤백
#122
=> [fix] 프로젝트 스탭 엔티티 수정 

src/main/resources/data.sql
- 시스템 어드민 샘플 데이터 추가
- 시스템 어드민 샘플 데이터 추가
- 어떻게 테스트했는지, 테스트 결과는 어땠는지 설명해주세요.
- #130 
<br>
=> [chore] 시스템 어드민 샘플 데이터 추가

src/main/java/kr/mywork/domain/company/service/dto/response/CompanySelectResponse.java, src/main/java/kr/mywork/infrastructure/company/rdb/QueryDslCompanyRepository.java, src/main/java/kr/mywork/interfaces/company/controller/dto/response/CompanySelectWebResponse.java, src/test/java/kr/mywork/docs/CompanyDocumentationTest.java
- 회사 목록 조회 응답 필드로 회사 아이디 추가
- 회사 목록 조회 응답 필드로 회사 아이디 추가
- #140 
<br>
=> [feat] 회사 목록 조회 응답 필드로 회사 아이디 추가

src/main/java/kr/mywork/interfaces/company/controller/CompanyController.java, src/main/java/kr/mywork/interfaces/member/controller/MemberController.java, src/test/java/kr/mywork/docs/CompanyDocumentationTest.java, src/test/java/kr/mywork/docs/MemberDocumentationTest.java
- 어떤 작업을 했는지 간단히 설명해주세요.
- `/api/member/company/{companyId}`-> `/api/companies/{companyId}/members`
- #143 
<br>
=> [feat] 회사 사원 목록 조회 URL 변경

src/main/resources/data.sql
- 프로젝트 초기 세팅을 위한 샘플 데이터 쿼리문 추가
- 회사 ID 사전 등록용 company_id 테이블 데이터 추가
- company 테이블에 DEV 및 CLIENT 유형의 샘플 회사 데이터 추가
- member 테이블에 SYSTEM_ADMIN, DEV_ADMIN, CLIENT_ADMIN 포함 다양한 역할의 샘플 유저 데이터 추가
- 시스템 관리자 및 회사 정보 초기 데이터 삽입
- 게시물 관련 화면페이지는 API미완성으로 오류납니다.
- DB에 직접 쿼리 실행하여 정상적으로 데이터가 삽입되는지 확인함
- 각 테이블 간 외래키 관계 오류 없이 INSERT 성공
- 쿼리 실행 후 SELECT로 데이터 조회하여 데이터 정합성 검증 완료
=> chore : 프로젝트 초기 세팅을 위한 샘플 데이터 쿼리문 추가

src/main/resources/data.sql
- 샘플 데이터 수정 및 관리자 추가
-  샘플데이터
#181
=> chore : 샘플 데이터 수정 및 관리자 추가

src/main/resources/data.sql
관리자 계정변경 비밀번호 변경
관리자 계정 변경 
admin@example.com
password1234
#187
=> fix: 관리자 이메일 비밀번호 변경 #187

src/main/java/kr/mywork/domain/post/model/Post.java, src/main/java/kr/mywork/domain/post/service/PostService.java
- 게시글이 삭제되지 않는 이슈 해결 (#190)
- @Transactional 어노테이션 누락으로 인한 문제
- 테스트 변화가 없습니다.
- #190 
<br>
=> [fix] 게시글이 삭제되지 않는 이슈 해결 (#190)

src/main/resources/data.sql
-샘플데이터 누락데이터 추가
-  샘플데이터 회사 추가 
#194
=> [fix] 샘플데이터 누락데이터 추가

src/main/java/kr/mywork/domain/member/model/Member.java, src/main/java/kr/mywork/domain/member/service/MemberService.java, src/main/java/kr/mywork/domain/member/service/dto/request/MemberUpdateRequest.java, src/main/java/kr/mywork/interfaces/member/controller/dto/request/MemberUpdateWebRequest.java, src/main/java/kr/mywork/interfaces/member/controller/dto/response/MemberDetailsWebResponse.java, src/test/java/kr/mywork/docs/MemberDocumentationTest.java
- 날짜 관련 필드 suffix 공통화
- day suffix -> Date 변경
- 목적 : FE 에서 날짜 관련 필드 기반으로 모듈하기 위함
- #202
=> [refactor] 날짜 관련 필드 suffix 공통화

src/main/java/kr/mywork/common/auth/config/SecurityConfig.java
- kbe-mywork.com CORS 추가 (#208)
- https://kbe-mywork.com 추가
- https://www.kbe-mywork.com 추가
- #208 
<br>
=> feat: kbe-mywork.com CORS 추가 (#208)

scripts/start.sh
- 서버 실행 spring.config.location 방식으로 변경
- spring.config.additional-location -> spring.config.location 방식으로 변경
- 수동 배포를 통한 정상 동작 확인 (이슈 참고)
- #227
<br>
- 이슈 참고
=> [build] spring.config.location 으로 실행 방식 변경

src/main/java/kr/mywork/domain/post/repository/PostRepository.java, src/main/java/kr/mywork/domain/post/service/PostService.java, src/main/java/kr/mywork/domain/post/service/dto/response/PostTotalCountInStepResponse.java, src/main/java/kr/mywork/domain/project_step/serivce/dto/request/ProjectStepDetailRequest.java, src/main/java/kr/mywork/domain/project_step/serivce/dto/response/ProjectStepPostTotalCountResponse.java, src/main/java/kr/mywork/infrastructure/post/rdb/QueryDslPostRepository.java, src/main/java/kr/mywork/interfaces/project_step/controller/ProjectStepController.java, src/main/java/kr/mywork/interfaces/project_step/dto/response/ProjectStepsWithPostTotalCountWebResponse.java, src/test/java/kr/mywork/docs/ProjectStepDocumentationTest.java, src/test/java/kr/mywork/interfaces/project_step/controller/ProjectStepControllerTest.java, src/test/resources/sql/project-step-get-with-count.sql
- 프로젝트 스탭 조회 API
- 프로젝트 스탭 조회시 totalCount 값 추가
#218
=> chore: 프로젝트 스탭 조회시 총 갯수 추가 #218

src/main/java/kr/mywork/domain/project/repository/ProjectRepository.java, src/main/java/kr/mywork/domain/project/service/ProjectService.java, src/main/java/kr/mywork/domain/project/service/dto/response/MyProjectSelectResponse.java, src/main/java/kr/mywork/infrastructure/project/rdb/QueryDslProjectRepository.java, src/main/java/kr/mywork/interfaces/project/controller/ProjectController.java, src/main/java/kr/mywork/interfaces/project/controller/dto/response/MyProjectListWebResponse.java, src/main/java/kr/mywork/interfaces/project/controller/dto/response/MyProjectSelectWebResponse.java, src/test/java/kr/mywork/docs/ProjectDocumentationTest.java, src/test/resources/sql/my-project-list.sql
- 내 프로젝트 리스트 조회 API
-  system 어드민이 아닌경우 내 프로젝트 리스트를 호출하는 API
#230
=> [feat] 내 프로젝트 리스트 조회 API

src/main/java/kr/mywork/domain/company/model/Company.java
- 이미지 업로드 및 로그 관리 병합 충돌 이슈 해결
- 필드명 변경
- #236 
- #233 
<br>
=> [fix] 이미지 업로드 및 로그 관리 병합 충돌 이슈 해결 (#237)

src/main/java/kr/mywork/common/api/components/filter/HttpLoggingFilter.java, src/main/java/kr/mywork/common/api/components/filter/RequestTrackingIdFilter.java, src/main/java/kr/mywork/common/api/components/request/HttpRequestBodyCachedWrapper.java, src/main/java/kr/mywork/common/api/components/request/RequestBodyCachedServletInputStream.java, src/main/java/kr/mywork/common/api/components/response/HttpResponseBodyCachedWrapper.java, src/main/java/kr/mywork/common/auth/config/SecurityConfig.java, src/main/java/kr/mywork/common/logging/AsyncConfig.java, src/main/java/kr/mywork/common/logging/LoggingFilterConfig.java, src/main/java/kr/mywork/common/logging/MDCTaskDecorator.java, src/main/resources/console-appender.xml, src/main/resources/file-error-appender.xml, src/main/resources/file-info-appender.xml, src/main/resources/file-warn-appender.xml, src/main/resources/logback-spring.xml
- API 로깅 필터 추가 및 요청 UUID 설정
- API 로깅 필터 설정
- RequestTrackingIdFilter 추가
- MDCDecorator 추가 (비동기 동작 시 다른 스레드 로컬에 UUID 전달하기 위함)
- #239
=> [feat] API 로깅 기능 개발

src/main/java/kr/mywork/domain/post/model/Post.java, src/main/java/kr/mywork/domain/post/service/PostService.java, src/main/java/kr/mywork/domain/post/service/dto/request/PostCreateRequest.java, src/main/java/kr/mywork/domain/post/service/dto/response/PostApprovalRequest.java, src/main/java/kr/mywork/domain/post/service/dto/response/PostApprovalResponse.java, src/main/java/kr/mywork/interfaces/post/controller/PostController.java, src/main/java/kr/mywork/interfaces/post/controller/dto/request/PostApprovalWebRequest.java, src/main/java/kr/mywork/interfaces/post/controller/dto/request/PostCreateWebRequest.java, src/main/java/kr/mywork/interfaces/post/controller/dto/response/PostApprovalWebResponse.java, src/test/java/kr/mywork/docs/PostDocumentationTest.java, src/test/resources/sql/post-for-approve.sql
=> [feat] 게시글 승인 API 구현

src/main/java/kr/mywork/domain/project/model/Project.java
-프로젝트 업데이트시 필드추가 (amount)
- 프로젝트 업데이트시 필드추가 (amount)
- 화면 테스트
#283
=> [chore] 프로젝트 업데이트시 필드추가 (amount)

.github/workflows/backend-cicd.yml
- main branch 푸시할 경우 CI/CD 자동화 설정
- github flow main branch 푸시할 경우 CI/CD 동작하도록 설정
=> [build] main branch 푸시할 경우 CI/CD 자동화 설정

.gitignore, docker/docker-compose.yml, docker/mysqld-exporter/.my.cnf, docker/prometheus/config/prometheus.yml, docker/rdb/initdb.d/init.sql
- grafana, prometheus docker-compose.yml 추가
- grafana, prometheus, mysql-exporter 추가
#336 
<br>
=> [build] grafana, prometheus docker-compose.yml 추가

.gitignore
- '.DS_Store' 파일을 git ignore에 추가
- #351
=> [chore]: '.DS_Store' 파일을 git ignore에 추가
